### PR TITLE
add `mirv_deathmsg` to AfxHookSource2

### LINKED ISSUE #868: CS2: mirv_deathmsg
mirv_deathmsg
basically only filter and extend time needed for most of people

### PR DESCRIPTION
**Pull request by ChetdeJong**
Closes https://github.com/advancedfx/advancedfx/issues/868

Make sure you give it a proper check before merging. Ideally compile and check commands in both csgo and cs2, especially new features.

Documentation:

Create page for command. I prepared one with markup, feel free to edit it, etc: 
https://pastebin.com/4KN9UnNM

Then link page in command list
https://github.com/advancedfx/advancedfx/wiki/Source2:Commands

Also consider linking page in release notes, because there are new features, so people can actually see it.

### CODE REVIEW

**Comment by Dechno1337** [comment]
The formatting for RGBA values should probably be without commas, and separate them with a space instead? I think that's how other commands are entered when having multiple values.

**Comment by Dechno1337** [comment]
Also, we (dtugend) don't use `help` sub commands. The [sub] commands should have the help text when not entering any value. The help text could be something similar to the wiki page info that you have written, for example:

User enters `mirv_deathmsg colors` and gets this in the console:
```
mirv_deathmsg colors ct <option> - Control CT color.
mirv_deathmsg colors t <option> - Control T color.
mirv_deathmsg colors border <option> - Control border color of local player.
mirv_deathmsg colors background <option> - Control background color.
mirv_deathmsg colors backgroundLocal <option> - Control background color of local player.

Where `<option>` it expect color in one of following formats:
- `default` use default game color for given element
- `i i i i` color in RGBA format e.g. `255 0 0 255` is solid red color
- `option` one of default provided colors e.g. `red`.

Maybe a list of colors here somewhere?
```
Etc.

I guess `mirv_deathmsg help players` was added in place of `mirv_listentities` ([since that hasn't been added yet](https://github.com/advancedfx/advancedfx/issues/874)(?))?

**Comment by ChetdeJong** [comment]
> Also, we (dtugend) don't use `help` sub commands. The [sub] commands should have the help text when not entering any value. The help text could be something similar to the wiki page info that you have written, for example:

I think that would be too much bloat in command since there is already plenty of info. However I can list them in single line probably, will check later how it looks.
> I guess `mirv_deathmsg help players` was added in place of `mirv_listentities` 

Yes, that's just easy way for ordinary user, instead of doing magic with mirv-script

**Comment by ChetdeJong** [comment]
ye actually doesnt look that bad, I updated pastebin too

**Review by dtugend — APPROVED** [review]

**Comment by dtugend** [comment]
Woah what a contribution, thank you very much.

**Pull request merged**
