### PR TITLE
Update HlaeErrors.cs

### PR DESCRIPTION
**Pull request by Dechno1337**
Fixed typos, updated some phrases and added a solution to case 5.

### CODE REVIEW

**Comment by Dechno1337** [comment]
Also, I hope the CloseAnthiCheatsSolution string isn't referenced in any other files since I fixed its typo. 😬

**Comment by dtugend** [comment]
> Also, I hope the CloseAnthiCheatsSolution string isn't referenced in any other files since I fixed its typo. 😬

It's only in that file I think.

**Comment by dtugend** [comment]
If you want to test your changes:
[hlae_2_114_0_1.zip](https://github.com/advancedfx/advancedfx/files/6548069/hlae_2_114_0_1.zip)

**Comment by dtugend** [comment]
Oh and thanks for the help of course :-)

**Pull request merged**
