### PR TITLE
mirv-script starter example

### PR DESCRIPTION
**Pull request by ChetdeJong**
Basic usage example, more info in readme

### CODE REVIEW

**Review by dtugend — APPROVED** [review]

**Review by dtugend — APPROVED** [review]

**Comment by ChetdeJong** [comment]
do not merge for now, will add few things later

**Comment by ChetdeJong** [comment]
Now the example is more complete. Check updated readme.

Later I think its possible to make it as npm package, when it will be in better shape. 
Only concern is bundling mirv.js

**Review by dtugend — APPROVED** [review]
Not too happy with the dependency on @osztenkurden, but ok.

**Review by ChetdeJong — COMMENTED** [review]
Looks good. 
I'll swap mine with yours then

**Comment by ChetdeJong** [comment]
just squashed last commit, forgot to update few things

**Pull request merged**
