### PR TITLE
Stop spectator camera from getting stuck into the ground.

### PR DESCRIPTION
**Pull request by mallgrab**
Moving the camera into the ground will get it stuck because PM_CatagorizePosition gets called from https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/pm_shared/pm_shared.c#L2965-L2970
This sticks the camera to the ground which makes it annoying to create camera angles that start from the ground since its very likely that you will accidently clip into the ground.
Hooking PM_CatagorizePosition and making it do nothing while also not calling its original function fixes the problem.

mirv_cstrike_spectator_fix off:
https://i.imgur.com/ZveZP2R.mp4

mirv_cstrike_spectator_fix on:
https://i.imgur.com/8I5f81s.mp4

### CODE REVIEW

**Comment by deprale** [comment]
Wow very good PR can't wait to use this!

**Comment by dtugend** [comment]
Hi. Thank you for your pull request.

I'd like to suggest a few changes:

## Cosmetic:
I know it doesn't matter much, but still I'd like to get the function signature of PM_CatagorizePosition correct, it's return type is void and not int.

## Relevant:
- We have access to ppmove, so the fix should only be applied when the player is in spectator / observer mode.
- Since we define the cvar we can access the cvar value directly.
- We should set a somewhat clean state on ppmove, since the original code is not run.
- Since we now check if we are spectator, it's safe to enable this feature by default in my opinion.

## Example pseudo code

```Cpp
// (specatorfix.cpp)
//..
#include "../../cmdregister.h" // instead of in filming.cpp do it here
//..
REGISTER_CVAR(cstrike_spectator_fix, "1", 0); // instead of in filming.cpp do it here

extern playermove_s *ppmove;

typedef void (__cdecl*UnkCstrikeSpectatorFn_t)();

//...
void __cdecl SpectatorFix_Hooking_Func()
{
	if( ( pmove->spectator || pmove->iuser1 > 0 ) && cstrike_spectator_fix->value != 0) {
		pmove->onground = -1;
		pmove->waterlevel = 0;
		pmove->watertype = CONTENTS_EMPTY;
		return;
	}

	g_pfnSpectatorFix_Hooked_Func();
}

```

---- ---- ---- ----

What do you think?

If you want and aggree I can carry out these changes for you,
or if you prefer to do them yourself that would be easier for me.

Edit: fixed missing onground value.

**Comment by mallgrab** [comment]
Sounds good, I wasn't sure if the method would have issues being hooked since both ida and ghidra were guessing the return type wrong but the hook still worked regardless. Needless to say I'll add the necessary changes to the pull request.

**Comment by dtugend** [comment]
Hi. Thank you very much for your contribution.
https://github.com/advancedfx/advancedfx/releases/tag/v2.134.0

**Pull request merged**
