### PR TITLE
Typos (ADVNACEDFX_STARTMOIVE)

### PR DESCRIPTION
**Pull request by Dechno1337**
`ADVNACEDFX_STARTMOIVE_WAV_KEY` -> `ADVANCEDFX_STARTMOVIE_WAV_KEY`

### CODE REVIEW

**Comment by dtugend** [comment]
I don't know - the typo is transparent to HLAE end-user, it doesn't appear in the binaries.
Should we really correct it? (Because a while ago we/I rejected someone fixing white space in the code.)

**Comment by Dechno1337** [comment]
Might as well, since it should only require 1 click (assuming I didn't mess anything up)?

**Comment by dtugend** [comment]
Please don't merge this pull request, it would generate 6 commits for what should be 1 - 2.
If anything, we should squash the commits (Squash and mere).

**Comment by dtugend** [comment]
If we quash the commits together and merge them it's ok, please use "Squash and Merge" option.

**Pull request merged**
