### PR TITLE
add `mirv_viewmodel` to AfxHookSource2

### LINKED ISSUE #941: CS2: mirv_viewmodel
Since left hand was added in CS2 it brought new issue.

Apparently looks like viewmodel is now part of demo (not sure though). 
Now it's not possible to change viewmodel anymore when watching demos. 
So every player has different viewmodel and left/right hand preference, which is I would rate as nightmare for video production.

Is it technically possible to hack these settings to force them to be something else?
Basically like `mirv_cvar_hack` was in CSGO.

However I think right/left hand might be tricky/impossible to fix since it plays animation when player changes hand.

Would be much appreciated if you can have a look to see if it's even possible to implement.

### PR DESCRIPTION
**Pull request by ChetdeJong**
Closes https://github.com/advancedfx/advancedfx/issues/941

Give it a check though. Maybe at very least you want to rename things/put in slightly different way

### CODE REVIEW

**Comment by dtugend** [comment]
Hi. Thanks for your contribution. I will have to look into the hook signatures you use in order to add some comments in the code or in doc/ folder of what these functions are and how to find them, because the signatures will probably break with the next larger CS2 update :S
Also if they are part of a vtable, it might be easier and more stable to use that to find them, but maybe they are not (didn't check yet).
I will try to do these tasks before Sunday (unless there's urgent CS2 update breakage of course).

**Comment by ChetdeJong** [comment]
well, these two are pretty straight forward I think, but I don't know if they are part of vtable or not.

Only thing is for some reason your `FindPatternString` can't find full pattern for second function (ghidra can find it though). So I shorten it a touch, but it's still unique.

Full signature for left/right hand function I got generated with [sigga](https://github.com/lexika979/Sigga) is `40 56 48 83 EC 20 80 B9 69 21 00 00 00 48 8B F1 ? ? 32 C0 48 83 C4 20 5E ? 48 8B 89`.

**Comment by dtugend** [comment]
(You need to put two question marks for a byte in FindPatternString , since it's for hex string, 2 hex digits are a byte.)

**Comment by ChetdeJong** [comment]
ye actually, I overlooked that. Works with full one

**Pull request merged**
