### PR TITLE
Added \n for `mirv_camio export end` error msg

### PR DESCRIPTION
**Pull request by FlowingSPDG**

### CODE REVIEW

**Comment by dtugend** [comment]
Hi.

It seems to me you are creating a slight mess on your end.

I can merge this without problems, but next time use an own branch on your end to work on and don't use pull requests to merge changes from the origin repro, just pull the master branch and then merge it with your own branch, otherwise you will create annoying unnecessary commits as is now.

Maybe read some basics about git branches.

**Comment by dtugend** [comment]
Now I made a mess too great D:

**Comment by dtugend** [comment]
Anyways, thanks for the fix / pull request :D

**Comment by FlowingSPDG** [comment]
Thanks for merge!
Sorry I'm new to git :( I'll do it next time!
Thanks for telling it :D keep it up

**Pull request merged**
