### PR TITLE
add `getCampath`

### PR DESCRIPTION
**Pull request by ChetdeJong**
Purpose: makes campath manipulation easier externally. 
e.g. get campath data and then manipulate with exec command. 

it does work, but I'm not sure if there are any caveats memory wise. I mostly followed your code as example.

### CODE REVIEW

**Comment by ChetdeJong** [comment]
`onCampathChange` hook might be useful too? Not sure for now

**Comment by dtugend** [comment]
Hi. Not sure if I'll merge this, because I wanted campath files to be objects like the websocket object is in mirv-script, since they then can be used in scripting (same for cam-io). I have to be very picky about the mirv-script API, because once it's done there's often no way back without breaking someone that depends on it being exctly like that.

**Comment by ChetdeJong** [comment]
Can you tell more about? Maybe it's something that I can do

**Comment by ChetdeJong** [comment]
I see. I may try to do it your way then. If not fully, then maybe in part. If you already know how to structure it (api), please let me know

**Comment by dtugend** [comment]
I will try to reply as soon as I can make sufficient time. Sorry.

**Comment by dtugend** [comment]
This will be notable work and might be not trivial.

The basic idea is to encapsulate the the _relevant_ features of the [CamPath](https://github.com/advancedfx/advancedfx/blob/main/shared/CamPath.h#L54) class into a javascript object that references it, this doesn't have to be 100% 1:1.

I did something similar already with the game entities.

Then we can add:
- mirv.newCamPath() - to make a new campath reference that can be used in scripting for other purposes
- mirv.getCamPath() - to get the main campath used in-game for mirv_campath command (not sure if we really need that)

A challenge here will be, that the main one must not be destoryable, but the other object one must be

And there should be a .destroy() or .delete() or some kind of finalizer function on CamPath object so that we can free underlying loaded campaths earlier than garbage collection of the object from script.

I also wanted to implement the quaternion math we have in AfxMath inside javascript mirv-script library, so we can use it in conjunction with campaths and other features that might use quaternions, but didn't have time yet.

This was my vision, but I haven't come around to implement it yet.

Edit: And I wanted to do a similar thing for mirv_camio xD

**Comment by ChetdeJong** [comment]
I see something like this, but it's different from what you suggested.

```cpp
class MirvCampath {

private: { 
    g_Campath // only this will be new, when instance created
    g_MirvCampath_Time // this is reference to global one
    g_MirvCampath_Camera // this is reference to global one 
    g_MirvCampath_Drawer // this is reference to global one 
}
public: {

// methods from `mirv_campath` command 
// + getCampath method so we have access to points info, that we can use with other methods.

}

}

```
So in JS we have Campath objects that mapped to `MirvCampath` class, so we have all methods available, but in JS will be extra `destroy` method.

With `mirv.newCampath()` we create new ones. In cpp it would be something like `new MirvCampath(new Campath, &g_MirvCampath_Time, &g_MirvCampath_Camera, &g_MirvCampath_Drawer)`.

Then we can set to main one like `mirv.setCampath(mirv.newCampath())`. It will create new reference and set it to initial g_MirvCampath global object, but we store initial one in g_MirvCampath_Initial.


If the `destroy` method will be called on one of the instances, that is currently set, then we just do `g_MirvCampath = 
g_MirvCampath_Initial` (and free memory ofc).

Will something like that work? If this approach will work, then I can do it. But not all methods for now, only get and maybe some few easy ones. Later we can add remaining ones.

or we need to expose everything separately like you suggested?

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/blob/3dc04fba71b75eb43f4d4de0b479eccbb62254cc/shared/CamPath.h#L54

**Comment by dtugend** [comment]
I think we have a misunderstanding here.

- With the current code it's not possible to set a new mirv_campath CamPath, only manipulate the existing one using the g_CamPath global object which is of class CamPath
- Instead I recommend to return a JavaScript wrapper around a reference to the CamPath class object/instance, but only when it was created with new and not derived from pointer to global g_CamPath it can and will be deleted (you just need a boolean and the pointer to track that in the wrapper / reference class you have to make for that in C++).

**Comment by ChetdeJong** [comment]
So is it not possible to just assign new Campath to global one? I didn't know that.

Well, I'll try to do it the way you said.

**Comment by ChetdeJong** [comment]
I put that on pause for a while, but will comeback later. If you want to do it yourself, then close it

**Comment by dtugend** [comment]
I started working on it. But it's gonna take quite a few weekends I think.

**Pull request closed without merging**
