### PR TITLE
mirv-script improvements

### PR DESCRIPTION
**Pull request by ChetdeJong**
Eslint now works properly, before it wasn't checking some files. Due to that now it shows if something isn't named consistently (I renamed few snippets files). Also there is a lot of diffs due formatting (prettier now applies as eslint rule).

Added `mirv-script-point` snippet. I exposed iterator from rust, please check if it's ok because I just copied similar code and I have no idea. It doesn't crash on me at least.

### CODE REVIEW

**Comment by dtugend** [comment]
Hi. Thank you for your pull request.

I know I often make the same mistake, but we should try to avoid cramming changes that are unrelated and independent into the same pull request if possible. I am specifically thinking of "expose campath iterator".

Please also notice that the campath iterator is already exposed:
https://github.com/advancedfx/advancedfx/blob/f0cdf53316a3e2f423898c2034868780e9287114/misc/mirv-script/src/types/campath.d.ts#L19 (`new AdvancedfxCampathIterator(campathObjectHere);`)

Is it really necessary to expose it a second time?

**Comment by ChetdeJong** [comment]
I see, sorry I just didn't think about it that you can just create iterator like that. I will revert that change now and adjust. 
The rest of things are more/less related, but maybe I could've split them into 2, yeah.

**Comment by ChetdeJong** [comment]
accidentally pushed commit here on wrong branch and removed now

**Comment by dtugend** [comment]
Thank you.

**Pull request merged**
